version: '3.6'
services:
  customer-assistant-api:
    image: "customer-assistant-api"
    user: 1000:1000
    build:
      context: ../..
      dockerfile: ./docker/debug/Dockerfile.debug.customer-assistant
    ports:
      - "127.0.0.1:8080:8080"
      - "127.0.0.1:5005:5005"
    volumes:
      - ../../customer-assistant/:/app/
    secrets:
      - demo
      - envFile

  customer-assistant-react-app:
    image: "customer-assistant-react-app"
    build:
      context: ../../
      dockerfile: ./docker/debug/Dockerfile.debug.ui
    ports:
      - "127.0.0.1:8081:3000"
    volumes:
      - ../../customer-assistant/src/main/webapp:/app/
  customer-assistant-web-server:
    image: "customer-assistant-web-server"
    depends_on:
      - customer-assistant-react-app
      - customer-assistant-api
    build:
      context: .
      dockerfile: ./Dockerfile.web-server
    ports:
      - "127.0.0.1:3000:80"
    environment:
      - API_URL=http://customer-assistant-api:8080
      - REACT_URL=http://customer-assistant-react-app:3000
secrets:
  demo:
    file: ../demo.properties
  envFile:
    file: ../../customer-assistant/.env
