version: '3.6'
services:
  customer-assistant-api:
    image: "customer-assistant-api"
    user: 1000:1000
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.customer-assistant
    secrets:
      - demo
      - envFile
    ports:
      - "8080:8080"
  customer-assistant-react-app:
    image: "customer-assistant-react-app"
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.ui
    environment:
      - API_URL=http://customer-assistant-api:8080
    ports:
      - "3000:80"
secrets:
  demo:
    file: ./demo.properties
  envFile:
    file: ./.env
