name: Build Java Semantic Kernel

# Triggers the workflow on manual dispatch, push, and pull request events
# for the specified branches and paths
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  # Builds and tests the Java project
  java-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - uses: actions/setup-java@b36c23c0d998641eff861008f374ee103c25ac73
        with:
          java-version: 21
          distribution: microsoft
          cache: maven

      - name: Build with Maven
        working-directory: ./
        run: ./mvnw -B clean install --file pom.xml

