name: Validate

# Triggers the workflow on manual dispatch, push, and pull request events
# for the specified branches and paths
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  # Builds and tests the Java project
  java-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - uses: actions/setup-java@b36c23c0d998641eff861008f374ee103c25ac73
        with:
          java-version: 21
          distribution: microsoft
          cache: maven

      - name: Build with Maven
        working-directory: ./
        run: ./mvnw -B clean install --file pom.xml

      - uses: microsoft/template-validation-action@v0.3.2
        with:
          workingDirectory: ./infra/aca
        id: validation
        env:
          AZURE_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
          AZURE_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
          AZURE_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
          AZURE_ENV_NAME: ${{ vars.AZURE_ENV_NAME }}
          AZURE_LOCATION: ${{ vars.AZURE_LOCATION }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: print result
        run: cat ${{ steps.validation.outputs.resultFile }}
